//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalGoods {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalGoods.ResourceMain", typeof(ResourceMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;ColumnName&quot;: &quot;BulletIndex&quot;,
        ///		&quot;DataType&quot;: &quot;INTEGER&quot;
        ///	},
        ///	{
        ///		&quot;ColumnName&quot;: &quot;BulletText&quot;,
        ///		&quot;DataType&quot;: &quot;TEXT&quot;,
        ///		&quot;Size&quot;: 255
        ///	},
        ///	{
        ///		&quot;ColumnName&quot;: &quot;CatalogBulletID&quot;,
        ///		&quot;DataType&quot;: &quot;INTEGER&quot;
        ///	},
        ///	{
        ///		&quot;ColumnName&quot;: &quot;CatalogBulletTicket&quot;,
        ///		&quot;DataType&quot;: &quot;TEXT&quot;,
        ///		&quot;Size&quot;: 36
        ///	},
        ///	{
        ///		&quot;ColumnName&quot;: &quot;CatalogImageID&quot;,
        ///		&quot;DataType&quot;: &quot;INTEGER&quot;
        ///	},
        ///	{
        ///		&quot;ColumnName&quot;: &quot;CatalogImageTicket&quot;,
        ///		&quot;DataType&quot;: &quot;TEXT&quot;,
        ///		&quot;Size&quot;: 36
        ///	},
        ///	{
        ///		&quot;ColumnName&quot;: &quot;CatalogItemCount&quot;,
        ///		&quot;DataType&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ColumnMetadata {
            get {
                return ResourceManager.GetString("ColumnMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c). 2020 Daniel Patterson, MCSD (danielanywhere)
        ///Released for public access under the MIT License.
        ///http://www.opensource.org/licenses/mit-license.php.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE
        ///FROM CatalogBullet
        ///WHERE CatalogBulletID IN({0});
        ///.
        /// </summary>
        internal static string delCatalogBulletForIDList {
            get {
                return ResourceManager.GetString("delCatalogBulletForIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE 
        ///FROM CatalogBullet
        ///WHERE CatalogBulletTicket IN({0});
        ///.
        /// </summary>
        internal static string delCatalogBulletForTicketList {
            get {
                return ResourceManager.GetString("delCatalogBulletForTicketList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE
        ///FROM CatalogImage
        ///WHERE CatalogImageTicket IN({0});
        ///.
        /// </summary>
        internal static string delCatalogImageForTicketList {
            get {
                return ResourceManager.GetString("delCatalogImageForTicketList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE
        ///FROM KeywordLocation
        ///WHERE
        ///KeywordLocationID IN(
        ///	SELECT KeywordLocationID
        ///	FROM KeywordLocation
        ///	INNER JOIN CatalogBullet ON
        ///	CatalogBullet.CatalogBulletID =
        ///	KeywordLocation.RecordID
        ///	INNER JOIN CatalogItem ON
        ///	CatalogItem.CatalogItemID =
        ///	CatalogBullet.CatalogItemID
        ///	WHERE
        ///	CatalogItem.CatalogItemID = {0} AND
        ///	KeywordLocation.TableIndexID = 1
        ///);
        ///.
        /// </summary>
        internal static string delKeywordLocationBulletForCatalogItemID {
            get {
                return ResourceManager.GetString("delKeywordLocationBulletForCatalogItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE
        ///FROM KeywordLocation
        ///WHERE
        ///KeywordLocationID IN(
        ///	SELECT KeywordLocationID
        ///	FROM KeywordLocation
        ///	INNER JOIN CatalogBullet ON
        ///	KeywordLocation.RecordID =
        ///	CatalogBullet.CatalogBulletID
        ///	WHERE
        ///	KeywordLocation.TableIndexID = 1 AND 
        ///	CatalogBullet.CatalogBulletTicket IN({0})
        ///);
        ///.
        /// </summary>
        internal static string delKeywordLocationBulletForTicketList {
            get {
                return ResourceManager.GetString("delKeywordLocationBulletForTicketList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE
        ///FROM KeywordLocation
        ///WHERE
        ///KeywordLocation.TableIndexID = 1 AND
        ///KeywordLocation.RecordID = {0} AND
        ///KeywordLocation.KeywordID NOT IN({1});
        ///.
        /// </summary>
        internal static string delKeywordLocationBulletItemNotInIDList {
            get {
                return ResourceManager.GetString("delKeywordLocationBulletItemNotInIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE
        ///FROM KeywordLocation
        ///WHERE
        ///KeywordLocation.TableIndexID = 3 AND
        ///KeywordLocation.RecordID = {0};
        ///.
        /// </summary>
        internal static string delKeywordLocationCatalogItemID {
            get {
                return ResourceManager.GetString("delKeywordLocationCatalogItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE
        ///FROM KeywordLocation
        ///WHERE
        ///KeywordLocation.TableIndexID = 3 AND
        ///KeywordLocation.RecordID = {0} AND
        ///KeywordLocation.KeywordID NOT IN({1});
        ///.
        /// </summary>
        internal static string delKeywordLocationCatalogItemNotInIDList {
            get {
                return ResourceManager.GetString("delKeywordLocationCatalogItemNotInIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO CatalogImage(
        ///CatalogImageTicket, 
        ///CatalogItemID, 
        ///ImageIndex, 
        ///ImageURL)
        ///VALUES ({0}, {1}, {2}, {3});
        ///.
        /// </summary>
        internal static string insCatalogImageWithTicket {
            get {
                return ResourceManager.GetString("insCatalogImageWithTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO CityRequest(
        ///CityRequestTicket,
        ///CityRequestName)
        ///SELECT
        ///{1} AS RequestTicket,
        ///{0} AS RequestName
        ///FROM CityRequest
        ///WHERE NOT EXISTS
        ///(
        ///	SELECT
        ///	CityRequest.CityRequestName
        ///	FROM
        ///	CityRequest
        ///	WHERE
        ///	CityRequest.CityRequestName = {0}
        ///);
        ///.
        /// </summary>
        internal static string insCityRequestAddUniqueName {
            get {
                return ResourceManager.GetString("insCityRequestAddUniqueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO UserItem(
        ///UserItemTicket,
        ///MemberUsername,
        ///MemberEmail,
        ///MemberPassword,
        ///CityItemID)
        ///VALUES ({0}, {1}, {2}, {3}, {4});
        ///.
        /// </summary>
        internal static string insUserItem {
            get {
                return ResourceManager.GetString("insUserItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username,email,add,all,alphanumeric,alter,and,any,application,as,asc,assistant,autoincrement,avg,between,binary,bit,boolean,by,byte,char,character,column,compactdatabase,constraint,container,count,counter,create,createdatabase,createfield,creategroup,createindex,createobject,createproperty,createrelation,createtabledef,createuser,createworkspace,currency,currentuser,database,date,datetime,delete,desc,description,disallow,distinct,distinctrow,document,double,drop,echo,else,end,eqv,error,exists,exit,false,fie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rwOleDB {
            get {
                return ResourceManager.GetString("rwOleDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username,email,add,all,alter,and,any,as,asc,backup,between,by,case,check,column,constraint,create,database,default,delete,desc,distinct,drop,exec,exists,foreign,from,full,group,having,in,index,inner,insert,into,is,join,key,left,like,limit,not,null,or,order,outer,primary,procedure,replace,right,rownum,select,set,table,top,truncate,union,unique,update,values,view,where,password.
        /// </summary>
        internal static string rwSQLDB {
            get {
                return ResourceManager.GetString("rwSQLDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?s:(?&lt;word&gt;\w+))).
        /// </summary>
        internal static string rxBasicSearchTerm {
            get {
                return ResourceManager.GetString("rxBasicSearchTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:^([a-z0-9]+([a-z0-9]|(?&lt;![_\-\.])[_\-\.])*)(?&lt;![_\-\.])@([a-z0-9]+([a-z0-9]|(?&lt;![_\-\.])[_\-\.])*)(?&lt;![_\-\.])\.([a-z]{2,5})$).
        /// </summary>
        internal static string rxValidEmail {
            get {
                return ResourceManager.GetString("rxValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE CatalogItem
        ///SET
        ///StarCount = {1},
        ///RatingCount = {2}
        ///WHERE CatalogItemID = {0};
        ///.
        /// </summary>
        internal static string upCatalogItemRate {
            get {
                return ResourceManager.GetString("upCatalogItemRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///CatalogBullet.*
        ///FROM CatalogBullet 
        ///WHERE CatalogBulletID = -1;
        ///.
        /// </summary>
        internal static string vwCatalogBulletBlank {
            get {
                return ResourceManager.GetString("vwCatalogBulletBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///CatalogBullet.BulletText,
        ///CatalogBullet.BulletIndex,
        ///CatalogBullet.CatalogBulletID,
        ///CatalogBullet.CatalogBulletTicket
        ///FROM CatalogBullet
        ///WHERE CatalogBullet.CatalogItemID = {0}
        ///ORDER BY
        ///CatalogBullet.BulletIndex,
        ///CatalogBullet.CatalogBulletID;
        ///.
        /// </summary>
        internal static string vwCatalogBulletForCatalogItemID {
            get {
                return ResourceManager.GetString("vwCatalogBulletForCatalogItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///CatalogBullet.*
        ///FROM CatalogBullet
        ///WHERE
        ///CatalogBullet.CatalogBulletTicket IN({0});
        ///.
        /// </summary>
        internal static string vwCatalogBulletForTicketList {
            get {
                return ResourceManager.GetString("vwCatalogBulletForTicketList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///CatalogImage.*
        ///FROM CatalogImage
        ///WHERE CatalogImageID = -1;
        ///.
        /// </summary>
        internal static string vwCatalogImageBlank {
            get {
                return ResourceManager.GetString("vwCatalogImageBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///CatalogImage.ImageURL,
        ///CatalogImage.ImageIndex,
        ///CatalogImage.CatalogImageID,
        ///CatalogImage.CatalogImageTicket
        ///FROM CatalogImage
        ///WHERE CatalogImage.CatalogItemID = {0}
        ///ORDER BY
        ///CatalogImage.ImageIndex,
        ///CatalogImage.CatalogImageID;
        ///.
        /// </summary>
        internal static string vwCatalogImageForCatalogItemID {
            get {
                return ResourceManager.GetString("vwCatalogImageForCatalogItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///CatalogItem.*
        ///FROM CatalogItem
        ///WHERE CatalogItemID = {0};
        ///.
        /// </summary>
        internal static string vwCatalogItem {
            get {
                return ResourceManager.GetString("vwCatalogItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///CatalogItem.*
        ///FROM CatalogItem
        ///WHERE CatalogItemID = -1;
        ///.
        /// </summary>
        internal static string vwCatalogItemBlank {
            get {
                return ResourceManager.GetString("vwCatalogItemBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///COUNT(CatalogItem.CatalogItemID) AS CatalogItemCount
        ///FROM CatalogItem
        ///INNER JOIN UserItem ON
        ///CatalogItem.UserItemID = UserItem.UserItemID
        ///GROUP BY UserItem.UserItemTicket
        ///HAVING UserItem.UserItemTicket = {0};
        ///.
        /// </summary>
        internal static string vwCatalogItemCountForUserTicket {
            get {
                return ResourceManager.GetString("vwCatalogItemCountForUserTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///CatalogItem.*,
        ///DepartmentItem.DepartmentName,
        ///UserItem.MemberUsername,
        ///CityItem.CityName
        ///FROM ((CatalogItem
        ///LEFT JOIN DepartmentItem ON
        ///CatalogItem.DepartmentItemID =
        ///DepartmentItem.DepartmentItemID)
        ///LEFT JOIN UserItem ON
        ///CatalogItem.UserItemID = UserItem.UserItemID)
        ///LEFT JOIN CityItem ON
        ///CatalogItem.CityItemID = CityItem.CityItemID
        ///WHERE CatalogItem.CatalogItemID = {0};
        ///.
        /// </summary>
        internal static string vwCatalogItemForID {
            get {
                return ResourceManager.GetString("vwCatalogItemForID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///CatalogItem.CatalogItemID
        ///FROM CatalogItem
        ///WHERE CatalogItem.CatalogItemTicket = {0};
        ///.
        /// </summary>
        internal static string vwCatalogItemIDForTicket {
            get {
                return ResourceManager.GetString("vwCatalogItemIDForTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///CatalogBullet.CatalogBulletID,
        ///CatalogBullet.CatalogItemID
        ///FROM CatalogBullet
        ///WHERE CatalogBulletID IN({0});
        ///.
        /// </summary>
        internal static string vwCatalogItemIDsForBulletIDs {
            get {
                return ResourceManager.GetString("vwCatalogItemIDsForBulletIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///CatalogItem.CatalogItemID,
        ///CatalogItem.CatalogItemTicket,
        ///CatalogItem.DepartmentItemID,
        ///CatalogItem.UserItemID,
        ///CatalogItem.DateCreated,
        ///CatalogItem.DateUpdated,
        ///CatalogItem.DateViewed,
        ///CatalogItem.Visible,
        ///CatalogItem.ViewCount,
        ///CatalogItem.ProductTitle,
        ///CatalogItem.ProductDescription,
        ///CatalogItem.StarCount,
        ///CatalogItem.ItemPrice,
        ///CatalogItem.ItemUnit,
        ///DepartmentItem.DepartmentName,
        ///CityItem.CityName,
        ///UserItem.CityItemID,
        ///(
        ///	SELECT
        ///	CatalogImage.ImageURL
        ///	FROM CatalogImage
        ///	WHE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vwCatalogItemsForCity {
            get {
                return ResourceManager.GetString("vwCatalogItemsForCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///CatalogItem.CatalogItemID,
        ///CatalogItem.CatalogItemTicket,
        ///CatalogItem.DepartmentItemID,
        ///CatalogItem.UserItemID,
        ///CatalogItem.DateCreated,
        ///CatalogItem.DateUpdated,
        ///CatalogItem.DateViewed,
        ///CatalogItem.Visible,
        ///CatalogItem.ViewCount,
        ///CatalogItem.ProductTitle,
        ///CatalogItem.ProductDescription,
        ///CatalogItem.StarCount,
        ///CatalogItem.ItemPrice,
        ///CatalogItem.ItemUnit,
        ///DepartmentItem.DepartmentName,
        ///CityItem.CityName,
        ///UserItem.CityItemID,
        ///(
        ///	SELECT
        ///	CatalogImage.ImageURL
        ///	FROM CatalogImage
        ///	WHE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vwCatalogItemsForIDList {
            get {
                return ResourceManager.GetString("vwCatalogItemsForIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///CatalogItem.CatalogItemID,
        ///CatalogItem.CatalogItemTicket,
        ///CatalogItem.DepartmentItemID,
        ///CatalogItem.UserItemID,
        ///CatalogItem.DateCreated,
        ///CatalogItem.DateUpdated,
        ///CatalogItem.DateViewed,
        ///CatalogItem.Visible,
        ///CatalogItem.ViewCount,
        ///CatalogItem.ProductTitle,
        ///CatalogItem.ProductDescription,
        ///CatalogItem.StarCount,
        ///CatalogItem.ItemPrice,
        ///CatalogItem.ItemUnit,
        ///DepartmentItem.DepartmentName,
        ///CityItem.CityName,
        ///UserItem.CityItemID,
        ///(
        ///	SELECT
        ///	CatalogImage.ImageURL
        ///	FROM CatalogImage
        ///	WHE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vwCatalogItemsForIDListInCity {
            get {
                return ResourceManager.GetString("vwCatalogItemsForIDListInCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///CatalogItem.CatalogItemID,
        ///CatalogItem.CatalogItemTicket,
        ///CatalogItem.DepartmentItemID,
        ///CatalogItem.UserItemID,
        ///CatalogItem.DateCreated,
        ///CatalogItem.DateUpdated,
        ///CatalogItem.DateViewed,
        ///CatalogItem.Visible,
        ///CatalogItem.ViewCount,
        ///CatalogItem.ProductTitle,
        ///CatalogItem.ProductDescription,
        ///CatalogItem.StarCount,
        ///CatalogItem.ItemPrice,
        ///CatalogItem.ItemUnit,
        ///DepartmentItem.DepartmentName,
        ///CityItem.CityName,
        ///UserItem.CityItemID,
        ///(
        ///	SELECT
        ///	CatalogImage.ImageURL
        ///	FROM CatalogImage
        ///	WHE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vwCatalogItemsForIDsAndUserTicket {
            get {
                return ResourceManager.GetString("vwCatalogItemsForIDsAndUserTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///CatalogItem.CatalogItemID,
        ///CatalogItem.CatalogItemTicket,
        ///CatalogItem.DepartmentItemID,
        ///CatalogItem.UserItemID, 
        ///CatalogItem.DateCreated,
        ///CatalogItem.DateUpdated,
        ///CatalogItem.DateViewed,
        ///CatalogItem.Visible,
        ///CatalogItem.ViewCount,
        ///CatalogItem.ProductTitle,
        ///CatalogItem.ProductDescription,
        ///CatalogItem.StarCount,
        ///CatalogItem.ItemPrice,
        ///CatalogItem.ItemUnit, 
        ///DepartmentItem.DepartmentName,
        ///UserItem.CityItemID,
        ///CityItem.CityName,
        ///(
        ///	SELECT
        ///	CatalogImage.ImageURL
        ///	FROM CatalogImage
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vwCatalogItemsForUserTicket {
            get {
                return ResourceManager.GetString("vwCatalogItemsForUserTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///FROM CityItem
        ///ORDER BY CityName;
        ///.
        /// </summary>
        internal static string vwCities {
            get {
                return ResourceManager.GetString("vwCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DepartmentItemID
        ///FROM DepartmentItem
        ///WHERE DepartmentItem.DepartmentName = {0};
        ///.
        /// </summary>
        internal static string vwDepartmentIDFromName {
            get {
                return ResourceManager.GetString("vwDepartmentIDFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///FROM DepartmentItem
        ///ORDER BY DepartmentItem.DepartmentName;
        ///.
        /// </summary>
        internal static string vwDepartments {
            get {
                return ResourceManager.GetString("vwDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///(COUNT(MemberEmail) = 0) AS EmailNotFound
        ///FROM UserItem
        ///WHERE MemberEmail = {0};
        ///.
        /// </summary>
        internal static string vwEmailNotFound {
            get {
                return ResourceManager.GetString("vwEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///KeywordLocation.*
        ///FROM KeywordLocation
        ///WHERE
        ///KeywordLocation.TableIndexID = 1 AND
        ///KeywordLocation.RecordID = {0} AND
        ///KeywordLocation.KeywordID IN({1});
        ///.
        /// </summary>
        internal static string vwKeywordLocationBulletItemInIDList {
            get {
                return ResourceManager.GetString("vwKeywordLocationBulletItemInIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///KeywordLocation.*
        ///FROM KeywordLocation
        ///WHERE
        ///KeywordLocation.TableIndexID = 3 AND
        ///KeywordLocation.RecordID = {0} AND
        ///KeywordLocation.KeywordID IN({1});
        ///.
        /// </summary>
        internal static string vwKeywordLocationCatalogItemInIDList {
            get {
                return ResourceManager.GetString("vwKeywordLocationCatalogItemInIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///Keyword.KeywordID,
        ///Keyword.KeywordName
        ///FROM Keyword
        ///ORDER BY
        ///Keyword.KeywordName;
        ///.
        /// </summary>
        internal static string vwKeywords {
            get {
                return ResourceManager.GetString("vwKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///Keyword.*
        ///FROM Keyword
        ///WHERE
        ///Keyword.KeywordName IN({0});
        ///.
        /// </summary>
        internal static string vwKeywordsForList {
            get {
                return ResourceManager.GetString("vwKeywordsForList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///KeywordLocation.RecordID,
        ///KeywordLocation.KeywordID,
        ///KeywordLocation.TableIndexID
        ///FROM KeywordLocation
        ///WHERE
        ///KeywordLocation.KeywordID IN({0});
        ///.
        /// </summary>
        internal static string vwRecordIDsForKeywordIDs {
            get {
                return ResourceManager.GetString("vwRecordIDsForKeywordIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///UserItem.UserItemID = {0} AND
        ///UserItem.UserItemTicket = {1} AS Result
        ///FROM UserItem
        ///WHERE UserItem.UserItemID = {0};
        ///.
        /// </summary>
        internal static string vwUserIDMatchesUserTicket {
            get {
                return ResourceManager.GetString("vwUserIDMatchesUserTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///UserItem.*
        ///FROM UserItem
        ///WHERE
        ///MemberEmail = {0} AND
        ///MemberPassword = {1};
        ///.
        /// </summary>
        internal static string vwUserItemForEmailPassword {
            get {
                return ResourceManager.GetString("vwUserItemForEmailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///UserItem.*
        ///FROM UserItem
        ///WHERE
        ///UserItem.UserItemTicket = {0} AND
        ///UserItem.MemberUsername = {1};
        ///.
        /// </summary>
        internal static string vwUserItemForTicketUsername {
            get {
                return ResourceManager.GetString("vwUserItemForTicketUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///UserItem.*
        ///FROM UserItem
        ///WHERE
        ///UserItemTicket = {0} AND
        ///([MemberEmail] = {1} OR
        ///[MemberPassword] = {2});
        ///.
        /// </summary>
        internal static string vwUserItemForTwoFactor {
            get {
                return ResourceManager.GetString("vwUserItemForTwoFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///UserItem.UserItemID
        ///FROM UserItem
        ///WHERE
        ///UserItem.UserItemTicket = {0};
        ///.
        /// </summary>
        internal static string vwUserItemIDForTicket {
            get {
                return ResourceManager.GetString("vwUserItemIDForTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///(COUNT(CatalogItem.CatalogItemID) &gt; 0) AS UserAuthorizedForCatalog
        ///FROM CatalogItem
        ///INNER JOIN UserItem ON
        ///CatalogItem.UserItemID =
        ///UserItem.UserItemID
        ///WHERE
        ///CatalogItem.CatalogItemID = {1} AND
        ///UserItem.UserItemTicket = {0};
        ///.
        /// </summary>
        internal static string vwUserItemTicketAuthorizedForCatalogItemID {
            get {
                return ResourceManager.GetString("vwUserItemTicketAuthorizedForCatalogItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///(COUNT(MemberUsername) = 0) AS UsernameNotFound
        ///FROM UserItem
        ///WHERE MemberUsername = {0};
        ///.
        /// </summary>
        internal static string vwUsernameNotFound {
            get {
                return ResourceManager.GetString("vwUsernameNotFound", resourceCulture);
            }
        }
    }
}
